--1
 SELECT * 
 FROM DEPT;

--2
  SELECT ENAME,JOB,HIREDATE,EMPNO
  FROM EMP;

--3
  SELECT ENAME,JOB,SAL AS 'MONTH_SAL',SAL*12 AS 'ANNUAL_SAL'
  FROM EMP;

--4
  SELECT ENAME + ' , ' + JOB AS 'EMPLOY AND DETAILS'
  FROM EMP;

--5
  SELECT DISTINCT JOB
  FROM EMP;

--6
  SELECT ENAME , SAL
  FROM EMP
  WHERE SAL > 2850;

--7
  SELECT ENAME,DEPTNO
  FROM EMP
  WHERE ENAME='SMITH';  

--8
  SELECT ENAME , JOB ,HIREDATE
  FROM EMP
  WHERE HIREDATE BETWEEN '1981-02-20' AND '1981-05-01'
  ORDER BY HIREDATE;

--9
  SELECT ENAME ,DEPTNO
  FROM EMP
  WHERE DEPTNO= 10 OR DEPTNO = 30 
  ORDER BY ENAME;

--10
   SELECT ENAME, HIREDATE 
   FROM EMP
   WHERE HIREDATE BETWEEN '1982-01-01' AND '1982-12-31';
  
--11
   SELECT ENAME , JOB 
   FROM EMP
   WHERE MGR IS NULL;

--12.
    SELECT GETDATE() AS 'DATE' ;

--13.
   SELECT e.ENAME , e.HIREDATE,m.ENAME,m.HIREDATE
   FROM EMP e,EMP m
   WHERE e.EMPNO = m.MGR AND e.HIREDATE < m.HIREDATE;

--14
   SELECT COUNT(JOB) AS 'NO_OF_MANAGER'
   FROM EMP
   WHERE JOB = 'MANAGER';

--15
   SELECT *
   FROM EMP
   WHERE DEPTNO IN (20,30,40);
   
--16
   select *
   FROM EMP
   WHERE ENAME LIKE 'T%R';

--17
   SELECT ENAME ,HIREDATE 
   FROM EMP
   WHERE DEPTNO = 30;

--18.
   
--19
   SELECT *
   FROM EMP
   WHERE JOB = 'ANALYST' AND  HIREDATE='1984-12-03';


    
--21
   SELECT JOB,DEPTNO, AVG(SAL*12) AS 'ANNUAL_SAL'
   FROM EMP
   GROUP BY JOB ,DEPTNO;
   
--22
   SELECT COUNT(SAL) AS 'TOTAL_SAL' ,COUNT(COMM) AS 'TOTAL_COMM'
   FROM EMP
   WHERE DEPTNO = 30 ;

--23.
   SELECT AVG(SAL) AS 'AVERAGE', MIN(SAL) AS 'MINIMUM', MAX(SAL) AS 'MAXIMUM'
   FROM EMP
   WHERE JOB = 'CLERK' OR JOB ='MANAGER' ;

--24.
   SELECT DEPTNO
   FROM EMP
   WHERE EXISTS (SELECT COUNT(JOB) AS CLERK_COUNT 
                FROM EMP
                WHERE JOB = 'CLERK'
                GROUP BY DEPTNO)
   GROUP BY DEPTNO;

--25
   SELECT ENAME , SAL
   FROM EMP
   WHERE SAL < (SELECT SAL*0.3 AS SAL
                 FROM EMP 
                 WHERE JOB= 'PRESIDENT');

--26
SELECT COUNT (EMP.ENAME)
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND LOC='Chicago';

--27
SELECT EMP.ENAME
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND LOC='Chicago';

--28
SELECT EMP.ENAME,LOC
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO
ORDER BY LOC;

--29
SELECT COUNT (ENAME)
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO;

--30
SELECT AVG(SAL) AS 'AVG_SAL'
FROM EMP;

--31
SELECT COUNT (DEPTNO)
FROM DEPT;

--32
SELECT DNAME,LOC,SUM(COMM) AS 'TOTAL_COMM'
FROM EMP,DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO;

--33
SELECT ENAME,JOB, SAL*12 AS 'ANNUAL'
FROM EMP;

--34
SELECT ENAME,JOB,COMM
FROM EMP
WHERE COMM IS NULL;

--35
SELECT ENAME,JOB,COMM
FROM EMP
WHERE COMM IS NOT NULL;

--36
SELECT ENAME,JOB,SAL
FROM EMP
WHERE ENAME	LIKE '__R%';

--37
SELECT *
FROM EMP
WHERE ENAME LIKE '_____';

--38
SELECT *
FROM EMP
WHERE ENAME NOT LIKE '_____';

--39
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%AR%';

--40
SELECT *
FROM EMP
WHERE DEPTNO=30
ORDER BY SAL;

--41
SELECT ENAME , SAL
FROM EMP
WHERE SAL >=1250 AND SAL <1600;

--42
SELECT ENAME , SAL
FROM EMP
WHERE SAL <1250 OR SAL >=1600;

--43
SELECT SUM(SAL) AS 'TOTAL_SAL'
FROM EMP;

--44
SELECT COUNT (ENAME)
FROM EMP
WHERE JOB IS NOT NULL;

--45
SELECT MIN(SAL) AS 'MIN_SAL', MAX(SAL) AS 'MAX_SAL'
FROM EMP;

--46
SELECT 
	EMPNO AS 'Emp#',
	ENAME AS 'Employee',
	SAL AS 'Salary',
	JOB,
	HIREDATE AS 'Date of Hire',
	COMM AS 'Commission',
	DEPTNO AS 'Department No',
	MGR AS 'MGR No'
FROM EMP;

--47
SELECT MIN(HIREDATE) AS 'EARLY' , MAX(HIREDATE) AS 'LATE'
FROM EMP;

--48
SELECT COUNT(ENAME)
FROM EMP
WHERE DEPTNO=10;

--49
SELECT ENAME,JOB,LOC,COMM
FROM DEPT,EMP
WHERE LOC='NEW YORK' AND COMM>10;