USE Training

CREATE TABLE PET(
PETID INT NOT NULL,
PNAME VARCHAR(14),
PTYPE VARCHAR(14),
PETA INT,
POWN VARCHAR(14),
VISIT DATE,
PROCEID INT,
PROCE VARCHAR(30));

CREATE TABLE PETINFO(
PETID INT NOT NULL,
PNAME VARCHAR(14),
PTYPE VARCHAR(14),
PETA INT,
POWN VARCHAR(14));

CREATE TABLE VISITD(
PETID INT,
VISIT DATE,
PROCE VARCHAR(30));

CREATE TABLE PROCED(
PROCEID INT,
PROCE VARCHAR(30));