SELECT ENAME,JOB
FROM EMP
WHERE JOB ='MANAGER';

SELECT ENAME,
  ( CASE WHEN JOB = 'SALESMAN'
  THEN 'SALES' ELSE 'NOT_SALES' END) JOB
  FROM EMP;

SELECT ENAME,
  (CASE WHEN SAL > 1000
    THEN SAL ELSE '1000' END) SAL
FROM EMP;

SELECT ENAME,
  (CASE WHEN SAL < 1000 THEN 'LOW'
       WHEN SAL BETWEEN 1000 AND 2500  THEN 'MEDIUM'
	   ELSE 'HIGH' END) SAL
FROM EMP;

SELECT ENAME,JOB,SAL
FROM EMP e
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='MILLER')
AND JOB='SALESMAN' ;

SELECT *
FROM EMP 
WHERE DEPTNO =( SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');

SELECT ENAME ,SAL,JOB
FROM EMP
WHERE SAL > ( SELECT MIN(SAL) FROM EMP WHERE JOB='MANAGER');

SELECT ENAME ,JOB
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');

SELECT COUNT(DEPTNO) AS 'COUNT'
FROM EMP 
WHERE DEPTNO =( SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');

SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC= 'CHICAGO');

SELECT DEPTNO,DNAME
FROM DEPT
WHERE DEPTNO NOT IN (SELECT DEPTNO FROM EMP);

SELECT ENAME ,JOB
FROM EMP
WHERE EMPNO NOT IN (SELECT EMPNO FROM EMP WHERE MGR IS NOT NULL);

SELECT ENAME,JOB 
FROM EMP 
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC= 'NEW YORK')
AND COMM > 1000;